# Generated by Django 3.2.3 on 2022-05-01 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerenciamento', '0003_hospital_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_pesquisa', to='gerenciamento.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitais_pesquisa', to='gerenciamento.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=700)),
                ('multipla_escolha', models.BooleanField(default=False)),
                ('opcoes', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas_pesquisa', to='pesquisa.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='pesquisa.alunopesquisa')),
                ('hospital_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='pesquisa.hospitalpesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField()),
                ('pergunta_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_pergunta', to='pesquisa.perguntapesquisa')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_pergunta', to='pesquisa.resposta')),
            ],
        ),
        migrations.AddField(
            model_name='resposta',
            name='respostas',
            field=models.ManyToManyField(through='pesquisa.RespostaPergunta', to='pesquisa.PerguntaPesquisa'),
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('coordenador_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas', to='gerenciamento.coordenador')),
                ('hospitais', models.ManyToManyField(through='pesquisa.HospitalPesquisa', to='gerenciamento.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='perguntapesquisa',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_pesquisa', to='pesquisa.pesquisa'),
        ),
        migrations.AddField(
            model_name='hospitalpesquisa',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitais_pesquisa', to='pesquisa.pesquisa'),
        ),
        migrations.AddField(
            model_name='alunopesquisa',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_pesquisa', to='pesquisa.pesquisa'),
        ),
    ]
