# Generated by Django 3.2.3 on 2022-05-04 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_auto_20220503_2238'),
        ('pesquisa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='multipla_escolha',
            field=models.BooleanField(default=False, verbose_name='Múltipla escolha'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='titulo',
            field=models.CharField(max_length=700, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='coordenador_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas', to='gerenciamento.coordenador', verbose_name='Coordenador responsável'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='data_fim',
            field=models.DateField(verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
    ]
