# Generated by Django 3.2.3 on 2022-05-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0006_auto_20220504_1032'),
        ('pesquisa', '0002_auto_20220503_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalpesquisa',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitais_pesquisa', to='gerenciamento.hospital'),
        ),
        migrations.AlterField(
            model_name='perguntapesquisa',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_pesquisa', to='pesquisa.pergunta'),
        ),
    ]
