# Generated by Django 3.2.3 on 2022-05-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0003_auto_20220514_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='perguntas',
            field=models.ManyToManyField(through='pesquisa.PerguntaPesquisa', to='pesquisa.Pergunta'),
        ),
    ]
