# Generated by Django 3.2.3 on 2022-05-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0004_pesquisa_perguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='titulo',
            field=models.CharField(max_length=500, verbose_name='Título'),
        ),
    ]
