# Generated by Django 3.2.3 on 2022-05-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0009_remove_aluno_pesquisas'),
        ('pesquisa', '0005_alter_pesquisa_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='alunos',
            field=models.ManyToManyField(through='pesquisa.AlunoPesquisa', to='gerenciamento.Aluno'),
        ),
    ]
