# Generated by Django 3.2.3 on 2022-04-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_aluno_coordenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('estado', models.CharField(max_length=300)),
                ('cidade', models.CharField(max_length=300)),
                ('tipo_local', models.CharField(choices=[('1', 'Interior'), ('2', 'Capital')], max_length=2)),
                ('tipo_organizacao', models.CharField(choices=[('1', 'Público'), ('2', 'Privado'), ('3', 'Federal')], max_length=2)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitais', to='gerenciamento.pais')),
            ],
        ),
    ]
