# Generated by Django 3.2.3 on 2022-05-04 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_aluno_pesquisas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='coordenador_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='gerenciamento.coordenador', verbose_name='Coordenador responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=13, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitais', to='gerenciamento.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='tipo_local',
            field=models.CharField(choices=[('1', 'Interior'), ('2', 'Capital')], max_length=2, verbose_name='Tipo do local'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='tipo_organizacao',
            field=models.CharField(choices=[('1', 'Público'), ('2', 'Privado'), ('3', 'Federal')], max_length=2, verbose_name='Tipo de organização'),
        ),
    ]
