# Generated by Django 3.2.3 on 2022-05-03 17:23

from django.db import migrations
from django.core.management import call_command


def load_command(apps, schema_editor):
    call_command("importar_paises")


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_auto_20220503_2238'),
    ]

    operations = [
        migrations.RunPython(load_command)
    ]
