# Generated by Django 3.2.3 on 2022-05-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0009_remove_aluno_pesquisas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', 'Coordenador'), ('2', 'Aluno')], default='1', max_length=2),
        ),
    ]
